# Generated by Django 4.1.7 on 2023-03-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.CharField(db_column='transactionid', max_length=100)),
                ('amount', models.CharField(db_column='amount', max_length=100)),
                ('phone', models.CharField(db_column='phone', max_length=100)),
            ],
            options={
                'verbose_name': 'checkout',
                'verbose_name_plural': 'checkouts',
                'db_table': 'checkout',
            },
        ),
    ]
